### ISSUE TITLE
Terminal screen overlaps when sharing terminal

### ISSUE THREAD

**Issue by diegoaguilar** [Share-Term/share-term#2]
I've noticed a few times I've tried share-term that my terminal screen will overlap or lines will struggle while typing. I've got this with maximized and minimized window using terminator in Ubuntu 14.04

**Comment by IonicaBizau** [comment]
:ship: `2.0.0` :tada: Hopefully, it got fixed by upgrading to `pty.js@0.3.0` :smile:

**Comment by diegoaguilar** [comment]
Thanks John! You're the best!

**Comment by IonicaBizau** [comment]
You're welcome! Thanks. :blush:
